---
mail_username: "{{ secret.smtp.username }}"
mail_password: "{{ secret.smtp.password }}"
mail_server: "{{ secret.smtp.server }}"
mail_port: "{{ secret.smtp.port }}"
mail_mailname: "{{ secret.smtp.mailname }}"
mail_recipient: "{{ secret.smtp.recipient }}"

system_locale: "en_US.UTF-8"
system_language: "en_US.UTF-8"



prometheus_endpoint: "https://mimir.call-cc.be/api/v1/push"

#----------------------------------------------------------------------------#
#                                Prometheus                                  #
#----------------------------------------------------------------------------#


prometheus_remote_write:
  - url: https://mimir.call-cc.be/api/v1/push

prometheus_external_labels:
  environment: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"
  hostname: "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}"

prometheus_scrape_configs:
  - job_name: "node"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9100"
        labels:
          host: "containers"